realValued
vector<vector<double> > realValued::Matrix
size_t realValued::rows
size_t realValued::columns
bool realValued::compare(realValued matrix)
void realValued::print_matrix()
bool realValued::correct_size_for_multiplication(const realValued matrix)
bool realValued::correct_sizes(const realValued matrix)
realValued realValued::multiplication(const realValued matrix)
realValued realValued::addition(realValued matrix)
realValued realValued::subtraction(realValued matrix)
void realValued::expand(const size_t &size)
realValued::realValued()=default
realValued::realValued(const int &n)
realValued::realValued(vector< vector< double >> matrix)
realValued::realValued(const size_t &N, const size_t &M, bool randInit=false)
void realValued::split(realValued &a1, realValued &a2, realValued &a3, realValued &a4)
Splits a real-valued matrix into four submatrices.
This method takes a real-valued matrix and splits it into four submatrices, each of size n/2 x n/2, where n is the size of the original matrix. The submatrices are stored in the passed parameters a1, a2, a3, and a4, respectively. a1 The first submatrix to store a2 The second submatrix to store a3 The third submatrix to store a4 The fourth submatrix to store : None
Referenced by Strassens_algorithm.
void realValued::collect(realValued &c11, realValued &c12, realValued &c21, realValued &c22)
Collects 4 submatrices to form a larger matrix. This method takes four realValued matrices (c11, c12, c21, c22) as input and combines them to form a larger matrix, with c11 in the top-left quadrant, c12 in the top-right quadrant, c21 in the bottom-left quadrant, and c22 in the bottom-right quadrant.
c11 The top-left quadrant matrix to be combined. c12 The top-right quadrant matrix to be combined. c21 The bottom-left quadrant matrix to be combined. c22 The bottom-right quadrant matrix to be combined. : void, as the method modifies the calling realValued object.
Referenced by Strassens_algorithm.
realValued realValued::Strassens_algorithm(realValued matrix, size_t n)
Implements Strassen's algorithm for multiplying two real-valued matrices. This function uses Strassen's algorithm to compute the product of two real-valued matrices of size n x n. If n is smaller than or equal to 64, the function uses standard matrix multiplication.
matrix The real-valued matrix to be multiplied with the current object n The size of the matrices : The product of the two matrices
References collect, split, Strassens_algorithm.
Referenced by Strassens_algorithm.
realValued realValued::Strassen_multiplication(realValued matrix)
Performs matrix multiplication using the Strassen algorithm. This function performs matrix multiplication using the Strassen algorithm, which is an algorithm for computing the product of two matrices. If the size of matrices is less than or equal to 64, it performs the regular multiplication. If the size is greater than 64, it expands the matrices to the nearest power of 2, and then applies the Strassen algorithm.
matrix The matrix to be multiplied with the calling object : The resulting matrix obtained after multiplication using Strassen algorithm runtime_error If the matrices are not of correct size for multiplication
Referenced by NewtonINversion::inverse.
auto realValued::test_time(const realValued &matrix)
auto realValued::test_time_Strassen(const realValued &matrix)
void realValued::test(const realValued &matrix)